server:
  port: 8080

spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: ms-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      mvc:
        routes:
        - id: users
          uri: http://localhost:8090
          predicates:
          - Path=/api/user/**
        - id: courses
          uri: http://localhost:9090
          predicates:
          - Path=/api/course/**

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG